"""empty message

Revision ID: 43355600985b
Revises: 96e384741578
Create Date: 2020-10-09 16:11:52.264162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43355600985b'
down_revision = '96e384741578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'end_time')
    # ### end Alembic commands ###
