"""empty message

Revision ID: db02590be7d2
Revises: 9db4d38dc0f7
Create Date: 2020-10-11 09:36:23.211196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db02590be7d2'
down_revision = '9db4d38dc0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('artist', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'album', 'artist', ['artist'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'album', type_='foreignkey')
    op.drop_column('album', 'artist')
    # ### end Alembic commands ###
